services:
  docs:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/mobipita-docs:cached
      - docs-node-modules:/workspaces/mobipita-docs/node_modules
      - pnpm-store:/home/node/.local/share/pnpm/store
    command: sleep infinity
    ports:
      - "4321:4321"
    init: true
    tty: true

volumes:
  docs-node-modules:
  pnpm-store:
